version: '3'
services:
  app:
    build:
      context: .
      target: dev
    volumes:
      - .:/app:cached
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
    command: |
      go run main.go start
    environment:
      DB_HOST: db
      DB_NAME: sample
      DB_USER: sample
      DB_PASS: sample

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: sample
      MYSQL_PASSWORD: sample
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - sample-mysql:/var/lib/mysql

volumes:
  sample-mysql:
