name: test
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        container:
            image: golang:1.20
        steps:
            - uses: actions/checkout@v2
            - name: test
              run: go test
